language: python
sudo: false
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy
env:
  - DJANGO=1.5.0
  - DJANGO=1.5.12
  - DJANGO=1.6.0
  - DJANGO=1.6.11
  - DJANGO=1.7.0
  - DJANGO=1.7.11
  - DJANGO=1.8.12
  - DJANGO=1.9.9
  - DJANGO=1.10.0
install:
    - pip install coveralls
    - pip install -q Django==$DJANGO
    - pip install -r requirements.txt
    - pip install -q Django==$DJANGO
script:
    - inv test
    - inv build
    - inv test_install
    - inv coverage
after_success:
    - coveralls
notifications:
    email: false
matrix:
  exclude:
    - python: 3.3
      env: DJANGO=1.4.0
    - python: 3.3
      env: DJANGO=1.4.20
    - python: 3.3
      env: DJANGO=1.10.0
    - python: 3.4
      env: DJANGO=1.4.0
    - python: 3.4
      env: DJANGO=1.4.20
    - python: pypy
      env: DJANGO=1.5
    - python: pypy
      env: DJANGO=1.5.12
