language: python
python:
    - "2.6"
    - "2.7"
    - "pypy"
install:
    - pip install coveralls --use-mirrors
script:
    - python setup.py test
    - python setup.py build
after_success:
    - coveralls
notifications:
    email: false