language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "pypy"
env:
    - DJANGO_VERSION=1.5
    - DJANGO_VERSION=1.6
    - DJANGO_VERSION=1.7
install:
    - pip install -q Django==$DJANGO_VERSION --use-mirrors
    - if [[ $TRAVIS_PYTHON_VERSION == 2.6 || $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install fabric --use-mirrors ; fi
    - pip install xmltodict --use-mirrors
    - pip install unittest2 --use-mirrors
    - pip install coveralls --use-mirrors
    - pip install nose --use-mirrors
    - pip install future --use-mirrors
    - pip install six --use-mirrors
script:
    - python setup.py build
    - python setup.py sdist
    - nosetests -v --with-coverage --cover-package=ares_util --cover-tests --cover-erase --with-doctest
after_success:
    - coveralls
notifications:
    email: false
