language: python
sudo: false
python:
# - 2.6
  - 2.7
  - 3.3
  - 3.4
# - pypy
# - nightly
env:
  - DJANGO=1.4.0
  - DJANGO=1.4.20
  - DJANGO=1.5.0
  - DJANGO=1.5.12
  - DJANGO=1.6.0
  - DJANGO=1.6.11
  - DJANGO=1.7.0
  - DJANGO=1.7.8
  - DJANGO=1.8.2
install:
    - easy_install -U pip & pip install setuptools wheel --upgrade
    - pip install -q Django==$DJANGO
    - if [[ $TRAVIS_PYTHON_VERSION != 3.3 || $TRAVIS_PYTHON_VERSION != 3.4 ]]; then pip install fabric unittest2; fi
    - if [[ $TRAVIS_PYTHON_VERSION == pypy ]]; then pip install future<15; else pip install future; fi
    - pip install xmltodict
    - pip install coveralls
    - pip install nose
    - pip install six
    - pip install requests
    - pip install travis
    - pip install flask
script:
    - python setup.py nosetests -v --with-coverage --cover-package=ares_util --cover-tests --cover-erase --with-doctest
    - python setup.py build
    - python setup.py sdist
    - python setup.py bdist_wheel
# before_script:
    # - flake8 .
after_success:
    - coveralls
notifications:
    email: false
matrix:
  exclude:
    # Taken from: https://github.com/darklow/django-suit/blob/develop/.travis.yml
    # Django doesn't support following combinations
    - python: 3.3
      env: DJANGO=1.4.0
    - python: 3.3
      env: DJANGO=1.4.20
    - python: 3.4
      env: DJANGO=1.4.0
    - python: 3.4
      env: DJANGO=1.4.20
    # Fails. Django issue #19944
    # https://code.djangoproject.com/ticket/19944
    - python: pypy
      env: DJANGO=1.5
    - python: pypy
      env: DJANGO=1.5.12
