language: python
sudo: false
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
env:
  - DJANGO=1.5.0
  - DJANGO=1.5.12
  - DJANGO=1.6.0
  - DJANGO=1.6.11
  - DJANGO=1.7.0
  - DJANGO=1.7.11
  - DJANGO=1.8.12
  - DJANGO=1.9.5
install:
    - easy_install -U pip & pip install setuptools wheel --upgrade
    - pip install -q Django==$DJANGO
    - pip install xmltodict
    - pip install coveralls
    - pip install nose
    - pip install six
    - pip install requests
    - pip install travis
    - pip install flask
    - pip install future
script:
    - rm -f fabfile.py
    - python setup.py build
    - python setup.py sdist
    - python setup.py bdist_wheel
    - python setup.py nosetests -v --with-coverage --cover-package=ares_util --cover-erase --with-doctest
after_success:
    - coveralls
notifications:
    email: false
matrix:
  exclude:
    - python: 3.3
      env: DJANGO=1.4.0
    - python: 3.3
      env: DJANGO=1.4.20
    - python: 3.4
      env: DJANGO=1.4.0
    - python: 3.4
      env: DJANGO=1.4.20
    - python: pypy
      env: DJANGO=1.5
    - python: pypy
      env: DJANGO=1.5.12
