language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
env:
  - DJANGO=1.4.5
  - DJANGO=1.5
  - DJANGO=1.5.5
  - DJANGO=1.6.5
  - DJANGO=1.7
install:
    - pip install -q Django==$DJANGO_VERSION --use-mirrors
    - if [[ $TRAVIS_PYTHON_VERSION != 3.3 || $TRAVIS_PYTHON_VERSION != 3.4 ]]; then pip install fabric unittest2 --use-mirrors ; fi
    - pip install xmltodict --use-mirrors
    - pip install coveralls --use-mirrors
    - pip install nose --use-mirrors
    - pip install future --use-mirrors
    - pip install six --use-mirrors
script:
    - python setup.py build
    - python setup.py sdist
    - nosetests -v --with-coverage --cover-package=ares_util --cover-tests --cover-erase --with-doctest
after_success:
    - coveralls
notifications:
    email: false
matrix:
  # Taken from: https://github.com/darklow/django-suit/blob/develop/.travis.yml
  exclude:
    # Django doesn't support following combinations
    - python: 3.3
    env: DJANGO=1.4.5
    - python: 3.4
    env: DJANGO=1.4.5
    - python: 2.6
    env: DJANGO=1.6.5
    - python: 2.6
    env: DJANGO=1.7

    # Fails. Django issue #19944
    # https://code.djangoproject.com/ticket/19944
    - python: pypy
    env: DJANGO=1.5
